export default {
  name: 'application',
  attributes: {
    domain_id: '',
    company_id: '',
    company_name: '',
    job_id: '',
    job_type: '',
    job_title: '',
    job_location: '',
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    attachments: [],
    application_at: '',
    downloaded: false,
    download_url: '',
    downloaded_at: '',
    hidden_at: '',
    hidden_by: '',
    available_files: '',
    deleted_at: '',
  },
};
