export default {
  name: 'company',
  id: '',
  attributes: {
    name: '',
    domain_id: '',
    description: '',
    publication_count: 0,
    address: {
      street: '',
      zipcode: '',
      city: '',
      state: '',
      country: '',
      lat: 0,
      lng: 0,
    },
    contact: {},
    logo_list_url: null,
    logo_profile_url: null,
    logo_profile_fb_url: null,
    employer_branding_profile_url: null,
    header_url: null,
    header_image_id: null,
    banner_exclusive_url: null,
    banner_region_url: null,
    banner_instructor_url: null,
    phone: '',
    fax: '',
    website_url: '',
    facebook_url: '',
    staffing_services: '',
    external_hrtool: false,
    collective_account: false,
    employees: 0,
    show_employees: false,
    company_is_public: true,
    use_new_jobmanagement: false,
    create_time: '',
    'active-flatrates': {
      jsonApi: 'hasMany',
      type: 'active-flatrate',
    },
    benefits: {
      jsonApi: 'hasMany',
      type: 'benefit',
    },
    'child-companies': {
      jsonApi: 'hasMany',
      type: 'company',
    },
    contacts: {
      jsonApi: 'hasMany',
      type: 'contact',
    },
    domains: {
      jsonApi: 'hasMany',
      type: 'domain',
    },
    employers: {
      jsonApi: 'hasMany',
      type: 'employer',
    },
    industry: {
      jsonApi: 'hasOne',
      type: 'industry',
    },
    jobs: {
      jsonApi: 'hasMany',
      type: 'job',
    },
    'main-contact': {
      jsonApi: 'hasOne',
      type: 'contact',
    },
    'parent-company': {
      jsonApi: 'hasOne',
      type: 'company',
    },
    'primary-domain': {
      jsonApi: 'hasOne',
      type: 'domain',
    },
    publications: {
      jsonApi: 'hasMany',
      type: 'publication',
    },
    'social-media-links': {
      jsonApi: 'hasMany',
      type: 'social-media-link',
    },
    subscriptions: {
      jsonApi: 'hasMany',
      type: 'subscription',
    },
    'gallery-pictures': {
      jsonApi: 'hasMany',
      type: 'gallery-picture',
    },
  },
};
