export default {
  name: 'contact',
  attributes: {
    company_id: null,
    salutation: null,
    title: null,
    firstname: null,
    lastname: null,
    job: null,
    occupation: null,
    department: null,
    responsibility: null,
    email: null,
    phone: null,
    mobile: null,
    fax: null,
    profile: false,
    image_url: null,
    show_in_company_profile: false,
    street: '',
    zipcode: '',
    city: '',
    country: '',
    image_uuid: '',
    address: {
      street: '',
      zipcode: '',
      city: '',
      state: '',
      country: '',
      lat: 0,
      lng: 0,
    },
  },
};
