export default {
  name: 'contact',
  attributes: {
    salutation: null,
    title: null,
    firstname: null,
    lastname: null,
    job: null,
    department: null,
    responsibility: null,
    email: null,
    phone: null,
    mobile: null,
    fax: null,
    profile: false,
    image_url: null,
    address: {
      street: '',
      zipcode: '',
      city: '',
      state: '',
      country: '',
      lat: 0,
      lng: 0,
    },
  },
};
